### PR TITLE
Generalized unit tests

### PR DESCRIPTION
**Pull request by marcoesters**
Prototype code to have a generalized unit test template so we can avoid code repetition.

This unfortunately requires conversion from yaml objects to strings, which I'm not super happy with...

This is just one example - I will expand once the structure is settled.

### CODE REVIEW

**Comment by danpetry** [comment]
> This unfortunately requires conversion from yaml objects to strings

Is it not possible to just write the strings into the test modules?

**Comment by razzlestorm** [comment]
> After talking to @danpetry, there is a design choice we have to make here. I personally am not happy with all that `yaml` juggling this PR is doing, but I also like the idea of separating test data and test code.
> 
> An alternative is to convert `TEST_DATA` into a dictionary like this:
> 
> ```
> TEST_DATA = [{
>         "name": "version_constraints_missing_whitespace_good",
>         "check": "version_constraints_missing_whitespace",
>         "add": """
>         requirements:
>           host:
>             - setuptools >=50
>         """,
>         "pass": True
>     },
>     {
>         "name": "version_constraints_missing_whitespace_bad",
>         "check": "version_constraints_missing_whitespace",
>         "add": """
>         requirements:
>           host:
>             - setuptools>=50
>         """,
>         "pass": False,
>         "message": "version constraints must be space separated",
>     },
> ]
> ```
> 
> and use strings instead. This list can be added to `test_lint.py` or `conftest.py`. Unfortunately, `yaml` has significant white space, so this makes adding multi-line strings a little less predictable.
> 
> @razzlestorm, what do you think?

I am more a fan of not filling up the tests directory with a bunch of test yaml files. If whitespace is an issue, I think creating a dict of data and using strings, then loading it using the Recipe class's `from_string` method seems fine. This way we could essentially have a 1:1 ratio of test files to lint files (the various different lints that are in anaconda_linter/lint).

**Review by razzlestorm — COMMENTED** [review]
Let's discuss in tomorrow's meeting which way makes the most sense, but my original thought was to have one test_X.py file for each lint, and to be creating the "yaml" (whether as a string or dict) to use inside of those test files. This makes it so we don't need to have multiple files for each test, and each test method remains relatively self-contained. I do get the idea that spacing could potentially be an issue if just using strings though, so a dict (or even a CommentSeq/CommentMap from ruamel.yaml) seems like a good compromise?

**Comment by danpetry** [comment]
Is there a way to define a Recipe object directly?

Also, I like the idea of one test per lint. I also like the idea of having the test data directly above the test code, so that you can see in one file what's being tested.

**Comment by razzlestorm** [comment]
> Is there a way to define a Recipe object directly?
> 
> Also, I like the idea of one test per lint. I also like the idea of having the test data directly above the test code, so that you can see in one file what's being tested.

Will test, right now we might need a render step, will investigate

**Comment by marcoesters** [comment]
I think I made the changes we discussed. This would make the `linter` fixture obsolete, but I left it there so that it doesn't break the spdx changes for now.

**Review by razzlestorm — APPROVED** [review]

**Pull request merged**
