### PR TITLE
Add package_in_general_cbc_yaml check

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Add `package_in_general_cbc_yaml` for checking if the package is mentioned inside the **general** `conda_build_config.yaml` file. 
It is advised to discuss if updating the package is really needed.

### CODE REVIEW

**Comment by marcoesters** [comment]
What is the use case for this check? Presumably, the package is updated for a reason.

I don't think it's within the scope of the linter to warn about whether a package needs updating, but to make sure the `meta.yaml` file is correct.

**Comment by razzlestorm** [comment]
I'm okay with implementing this as a warning, if people want. Do we have an example package this could work on?

**Comment by skupr-anaconda** [comment]
> I'm okay with implementing this as a warning, if people want. Do we have an example package this could work on?

E.g., libtiff is a good one https://github.com/AnacondaRecipes/aggregate/blob/2571541605ef1cb6ebd471fd27b95ea07c2a3514/conda_build_config.yaml#L128 if we would update it to the latest version then many complicated packages should be updated too. That's why we apply security patches to the current version and don't update the version. Other packages from the general cbc.yaml file have the same problem. So the warning for the package builder will avoid the useless work.

**Comment by razzlestorm** [comment]
Now that we have tests in main, could you also implement a quick unit test for this to make sure we don't break the lint somehow in the future?

**Comment by marcoesters** [comment]
As of now, the Prefect flow lets the linter check fail even with `INFO`. I think we need to be cautious about what these types of unfixable checks will do. I personally would be prefer this to be `INFO`, but we need to have a discussion about the scope of the linter and how this influences the Prefect flow.

**Pull request closed without merging**
